import { Category } from './category';
import { Product } from './product';

export const PRODUCTS: Product[] = [
  {
    image: '../../assets/images/cropped/1.jpg',
    thumb: '../../assets/images/thumbs/1.jpg',
    title: 'Tennis Mustache',
    price: 24.99,
    description:
      'Relive the glory days of tennis with this 1970s inspired tennis brand mustache. It is sure to be a hit!',
    tags: ['unisex', 'tennis', 'costume', 'mustache'],
    category: Category.COSTUMES,
    id: '1',
  },
  {
    image: '../../assets/images/cropped/2.jpg',
    thumb: '../../assets/images/thumbs/2.jpg',
    title: 'Scuba Stuff',
    price: 129.99,
    description:
      'Since people cannot breathe underwater, if you want to go hang out with sea turtles, you will need some scuba stuff. This set has all the stuff you need, but someone should show you how to use it.',
    tags: ['scuba', 'swimming', 'turtles', 'unisex', 'bio-degradable'],
    category: Category.UNDERWATER,
    id: '2',
  },
  {
    image: '../../assets/images/cropped/3.jpg',
    thumb: '../../assets/images/thumbs/3.jpg',
    title: 'Old Timey Scuba Stuff',
    price: 418.99,
    description:
      'If you want to go underwater where humans cannot breathe but you want to feel really really heavy, you might like this old timey scuba thing.',
    tags: ['scuba', 'swimming', 'coral reefs', 'pirates', 'business attire'],
    category: Category.UNDERWATER,
    id: '3',
  },
  {
    image: '../../assets/images/cropped/4.jpg',
    thumb: '../../assets/images/thumbs/4.jpg',
    title: 'Swimming Hat',
    price: 8.99,
    description:
      'When people go swimming they wear hats and you do not want to feel left out do you? This hat is green and it is stretchy so it will probably fit your giant head.',
    tags: ['hat', 'swimming', 'scuba', 'fashionable', 'chic'],
    category: Category.UNDERWATER,
    id: '4',
  },
  {
    image: '../../assets/images/cropped/5.jpg',
    thumb: '../../assets/images/thumbs/5.jpg',
    title: 'Big Swimming Feet',
    price: 32.99,
    description:
      'Are your feet too small for swimming? These big plastic swimming feet can help! They are unisex and go with everything!',
    tags: ['shoes', 'swimming', 'fashion', 'unisex', 'underwater'],
    category: Category.UNDERWATER,
    id: '5',
  },
  {
    image: '../../assets/images/cropped/6.jpg',
    thumb: '../../assets/images/thumbs/6.jpg',
    title: 'Tennis Ball',
    price: 3.99,
    description:
      'It is a ball that people play tennis with. You get one.',
    tags: ['ball', 'tennis', 'green', 'danger', 'adults-only'],
    category: Category.BALLS,
    id: '6',
  },
  {
    image: '../../assets/images/cropped/7.jpg',
    thumb: '../../assets/images/thumbs/7.jpg',
    title: 'Swimming Mask',
    price: 12.99,
    description:
      "This mask is perfect if you do not want fish to recognize you. It covers basically your whole face. Not even octopi will recognize you.",
    tags: ['swimming', 'disguise', 'cool', 'incognito'],
    category: Category.UNDERWATER,
    id: '7',
  },
  {
    image: '../../assets/images/cropped/8.jpg',
    thumb: '../../assets/images/thumbs/8.jpg',
    title: 'Football',
    price: 15.99,
    description:
      'This is a football. Americans will argue about it, but it is a football',
    tags: ['football', 'ball', 'thing to kick', 'soccer'],
    category: Category.BALLS,
    id: '8',
  },
  {
    image: '../../assets/images/cropped/9.jpg',
    thumb: '../../assets/images/thumbs/9.jpg',
    title: 'Tiny Football for Tiny Humans',
    price: 8.99,
    description:
      'Are you tired of your violent child kicking you? Get them a ball to kick instead! They will get so tired kicking it you might get some alone time.',
    tags: ['ball', 'football', 'baby', 'violent baby'],
    category: Category.BALLS,
    id: '9',
  },
  {
    image: '../../assets/images/cropped/10.jpg',
    thumb: '../../assets/images/thumbs/10.jpg',
    title: 'Embroidered Sash Award',
    price: 129.99,
    description:
      'Is your name Dmitriy? It is probably less confusing if it is because that is the only name we can sew on this sash. People win it for being real strong.',
    tags: ['award', 'sash', 'trophy', 'muscles', 'dmitriy'],
    category: Category.TROPHIES,
    id: '10',
  },
  {
    image: '../../assets/images/cropped/11.jpg',
    thumb: '../../assets/images/thumbs/11.jpg',
    title: 'Child Sized Football Trophy',
    price: 9.99,
    description:
      'Give you kid an award for being a good ball kicker! We can also make this one to match your child if they wear more blue.',
    tags: ['trophy', 'football', 'kid', 'participation award', 'tube socks'],
    category: Category.COSTUMES,
    id: '11',
  },
  {
    image: '../../assets/images/cropped/12.jpg',
    thumb: '../../assets/images/thumbs/12.jpg',
    title: 'Long Green Socks',
    price: 25.99,
    description:
      'These long lime green socks will keep your legs warm and help to convince people that you play football. We do not sell matching shows so you will have to do your best.',
    tags: ['socks', 'legs', 'football', 'get to work', 'unisex'],
    category: Category.COSTUMES,
    id: '12',
  },
  {
    image: '../../assets/images/cropped/13.jpg',
    thumb: '../../assets/images/thumbs/13.jpg',
    title: 'A Bunch of Trophies',
    price: 67.99,
    description:
      'Are you not sure which sport you will excel at? That is ok, you can buy this set of trophies that include one trophy for each of these sports: football, basketball, and excellent posture.',
    tags: ['excellent posture', 'trophy', 'treat yo self', 'prize', 'football'],
    category: Category.TROPHIES,
    id: '13',
  },
  {
    image: '../../assets/images/cropped/14.jpg',
    thumb: '../../assets/images/thumbs/14.jpg',
    title: 'Concave Plastic Disc Things',
    price: 50.99,
    description:
      'This is a whole set of smallish concave plastic discs that have their own carrier thing. We found them in the football department so they are probably for that.',
    tags: ['football?', 'plastic shape', 'pile', 'concave disc', 'cone?'],
    category: Category.EQUIPMENT,
    id: '14',
  },
  {
    image: '../../assets/images/cropped/15.jpg',
    thumb: '../../assets/images/thumbs/15.jpg',
    title: 'Everything Basketball',
    price: 97.99,
    description:
      'We pride ourselves for being a one stop shop, and if you want to take up basket ball, this set has everything but the hoop. It has three matching jerseys, a ball, three awards, and one team trophy to fight over. The only color is orange.',
    tags: ['orange', 'basketball', 'team power', 'dribble', 'ball'],
    category: Category.BALLS,
    id: '15',
  },
  {
    image: '../../assets/images/cropped/16.jpg',
    thumb: '../../assets/images/thumbs/16.jpg',
    title: 'Slightly Used Football Kicking Net',
    price: 14.99,
    description:
      'This used to belong to my cousin Paul. He has arthritis in his knee so he won\'t miss it. I can deliver but it will cost you.',
    tags: ['kicking net', 'winning', 'do not tell Paul', 'football', 'dude'],
    category: Category.EQUIPMENT,
    id: '16',
  },
  {
    image: '../../assets/images/cropped/17.jpg',
    thumb: '../../assets/images/thumbs/17.jpg',
    title: 'Tennis Racket with Trophy Set',
    price: 48.99,
    description:
      'It has a racket, a sweatband thing that has not been used, one ball, an award to wear on date nights, and a trophy shaped cup to hold you ball when you are not using it.',
    tags: ['tennis', 'racket', 'trophy', 'cool', 'sweatband'],
    category: Category.HITTING_THINGS,
    id: '17',
  },
  {
    image: '../../assets/images/cropped/18.jpg',
    thumb: '../../assets/images/thumbs/18.jpg',
    title: 'Matching Snowpants',
    price: 68.99,
    description:
      'Why go skiing with friends if you do not match. These two pairs of snowpants come in random sizes which will help you make friends of new shapes and sizes. Hit the slope!',
    tags: ['pants', 'unisex', 'skiing', 'cold', 'mountains'],
    category: Category.COSTUMES,
    id: '18',
  },
  {
    image: '../../assets/images/cropped/19.jpg',
    thumb: '../../assets/images/thumbs/19.jpg',
    title: 'Handful of Random Medals',
    price: 24.99,
    description:
      'It is a good idea to always have medals around to award people who perform well at sports. These have random numbers on them and may or may not be for sports.',
    tags: ['award', 'trophy', 'successful', 'professional', 'teamwork'],
    category: Category.TROPHIES,
    id: '19',
  },
  {
    image: '../../assets/images/cropped/20.jpg',
    thumb: '../../assets/images/thumbs/20.jpg',
    title: 'Ned Flanders Inspired Skiing Costume for Racing',
    price: 93.99,
    description:
      'It will feel like you are wearing nothing at all! Except you will be wearing a ski racing suit so you might want to wear it while you are skiing or near a ski town.',
    tags: ['skiing', 'race', 'fast', 'Stupid Sexy Flanders', 'tight'],
    category: Category.SPEED,
    id: '20',
  },
  {
    image: '../../assets/images/cropped/21.jpg',
    thumb: '../../assets/images/thumbs/21.jpg',
    title: 'Helmet with Shiny Sunglasses',
    price: 31.99,
    description:
      'This helmet will help protect your identity because people cannot see through the reflective sunglasses. But don\'t worry, YOU CAN! We think it is for skiing but it will also look cool on a bike.',
    tags: ['helmet', 'racing', 'disguise', 'shiny', 'sunshine hat'],
    category: Category.SPEED,
    id: '21',
  },
  {
    image: '../../assets/images/cropped/22.jpg',
    thumb: '../../assets/images/thumbs/22.jpg',
    title: 'Tennis High Chair',
    price: 131.99,
    description:
      'Do you have a hard time seeing the ball at tennis games? We do too, that is why we invented this super cool and safe high chair for tennis games.',
    tags: ['high chair', 'best seat in town', 'tennis'],
    category: Category.EQUIPMENT,
    id: '22',
  },
  {
    image: '../../assets/images/cropped/23.jpg',
    thumb: '../../assets/images/thumbs/23.jpg',
    title: 'Flipping Number Cards',
    price: 18.99,
    description:
      'If you understand how to keep score in tennis, these might be helpful to you. If not, have fun flipping the cards!',
    tags: ['numbers', 'tennis', 'scoreboard', 'activities', 'paper'],
    category: Category.EQUIPMENT,
    id: '23',
  },
  {
    image: '../../assets/images/cropped/24.jpg',
    thumb: '../../assets/images/thumbs/24.jpg',
    title: 'Rugby Ball Chair',
    price: 12.99,
    description:
      'This little blue dealie holds a ball so you can kick it? It is shaped for a rugby ball but they kind of look like American footballs so it might also work for that.',
    tags: ['rugby', 'plastic thing', 'blue', 'kicking', 'ball'],
    category: Category.EQUIPMENT,
    id: '24',
  },
  {
    image: '../../assets/images/cropped/26.jpg',
    thumb: '../../assets/images/thumbs/26.jpg',
    title: 'Fast Red Car',
    price: 6125.99,
    description:
      "Slightly used red car that goes pretty fast on dirt roads. It has numbers on it so you will always be racing.",
    tags: ['used car', 'drive', 'fast', 'speed demon', 'race car'],
    category: Category.SPEED,
    id: '26',
  },
  {
    image: '../../assets/images/cropped/25.jpg',
    thumb: '../../assets/images/thumbs/25.jpg',
    title: 'Dirty Bike',
    price: 511.99,
    description:
      'For an extra charge we will wash this dirty bike before we ship it to you. Otherwise it comes pre-dirty.',
    tags: ['dirty', 'mud', 'racing', 'motorcycle', 'bike'],
    category: Category.SPEED,
    id: '25',
  },

  {
    image: '../../assets/images/cropped/27.jpg',
    thumb: '../../assets/images/thumbs/27.jpg',
    title: 'Pickle Balls',
    price: 3.99,
    description:
      'We did not really believe this was a real sport but it is. Elderly Americans like to play at abandoned shopping malls.',
    tags: ['pickle ball', 'made up sport', 'whiffle ball', 'ball'],
    category: Category.BALLS,
    id: '27',
  },
  {
    image: '../../assets/images/cropped/28.jpg',
    thumb: '../../assets/images/thumbs/28.jpg',
    title: 'Cowboy Style Horse',
    price: 665.99,
    description:
      'This horse is the perfect horse for a cowboy or girl. It comes with a saddle and a cowboy hat. This horse does not qualify for free shipping.', 
    tags: ['horse', 'fed ex only', 'hat', 'cowboy', 'cowgirl'],
    category: Category.HORSE_SPORTS,
    id: '28',
  },
  {
    image: '../../assets/images/cropped/29.jpg',
    thumb: '../../assets/images/thumbs/29.jpg',
    title: 'Sticks For Your Horse to Jump',
    price: 31.99,
    description:
      'Did you buy a jumping horse from us last year and forget to buy jumping sticks? Do not despair, we have some extras.',
    tags: ['sticks', 'jumping', 'horses', 'dressage', 'racing'],
    category: Category.HORSE_SPORTS,
    id: '29',
  },
  {
    image: '../../assets/images/cropped/30.jpg',
    thumb: '../../assets/images/thumbs/30.jpg',
    title: 'Tiny Golf Car',
    price: 811.99,
    description:
      'This miniature car is perfect for driving around a golf course or a retirement community in Florida. It is so easy to drive even children drive it.',
    tags: ['golf car', 'tiny car', 'economy', 'electric vehicle', 'kids'],
    category: Category.EQUIPMENT,
    id: '30',
  },
  {
    image: '../../assets/images/cropped/32.jpg',
    thumb: '../../assets/images/thumbs/32.jpg',
    title: 'Golf Ball Bucket',
    price: 21.99,
    description:
      'This bucket is perfect for holding balls. The model is demonstrating how it holds golf balls. It is too small for larger balls like basketballs. Golf balls not included.',
    tags: ['golf', 'whiffle balls', 'ping pong balls', 'fancy', 'basket'],
    category: Category.EQUIPMENT,
    id: '32',
  },
  {
    image: '../../assets/images/cropped/32.jpg',
    thumb: '../../assets/images/thumbs/32.jpg',
    title: 'Golf Balls (no bucket)',
    price: 21.99,
    description:
      'This is a whole bunch of golf balls. Specifically it is a bucket full of golf balls but the bucket is not included.',
    tags: ['golf', 'golf balls for days', 'no bucket'],
    category: Category.BALLS,
    id: '32a',
  },
  {
    image: '../../assets/images/cropped/33.jpg',
    thumb: '../../assets/images/thumbs/33.jpg',
    title: 'Ice Shoes',
    price: 21.99,
    description:
      'These shoes have sharp metal blades on the bottom that are perfect for going on the ice. These should not be worn on hard wood floors.',
    tags: ['shoes', 'metal blades', 'ice', 'not for indoor use', 'speed'],
    category: Category.COSTUMES,
    id: '33',
  },
  {
    image: '../../assets/images/cropped/34.jpg',
    thumb: '../../assets/images/thumbs/34.jpg',
    title: 'Spirit Clothing',
    price: 31.99,
    description:
      'Cheer on your favorite sport team with this giant bow and plastic pom poms set. Comes in red, black, green, or blue',
    tags: ['pom poms', 'spectators', 'biggest fan', 'bow', 'cheer'],
    category: Category.SPECTATORS,
    id: '34',
  },
  {
    image: '../../assets/images/cropped/35.jpg',
    thumb: '../../assets/images/thumbs/35.jpg',
    title: 'Face Paints',
    price: 19.99,
    description: "You know you want to be that guy. Choose up to three different tubs of paint guaranteed to eventually wash off. Might cause skin reaction.",
    tags: ['paint', 'biggest fan', 'sports', 'black', 'washable'],
    category: Category.SPECTATORS,
    id: '35',
  },
  {
    image: '../../assets/images/cropped/36.jpg',
    thumb: '../../assets/images/thumbs/36.jpg',
    title: 'Horn for Sports',
    price: 34.99,
    description:
      'Be the loudest person in the crowd with this brass sports horn. You don\'t even have to know how to play an instrument because this thing only plays one note anyway!',
    tags: ['horn', 'party', 'loud', 'festive', 'annoying'],
    category: Category.SPECTATORS,
    id: '36',
  },
  {
    image: '../../assets/images/cropped/37.jpg',
    thumb: '../../assets/images/thumbs/37.jpg',
    title: 'Matching Sports Glasses',
    price: 18.99,
    description:
      'You and your besting can show off your team spirit with these matching sport sunglasses! Pair them with a horned hat or some mardi gras beads.',
    tags: ['besties', 'sunglasses', 'pair', 'biggest fan', 'party'],
    category: Category.SPECTATORS,
    id: '37',
  },
  {
    image: '../../assets/images/cropped/38.jpg',
    thumb: '../../assets/images/thumbs/38.jpg',
    title: 'Green Fake Teeth',
    price: 19.99,
    description:
      'Confuse the person trying to fight you by wearing these fake green teeth. They will wonder why your teeth are green and then you can punch them in the nose.',
    tags: ['boxing', 'fake teeth', 'plastic', 'green', 'costume'],
    category: Category.HITTING_THINGS,
    id: '38',
  },
  {
    image: '../../assets/images/cropped/39.jpg',
    thumb: '../../assets/images/thumbs/39.jpg',
    title: 'Overstuffed Mittens for Punching',
    price: 73.99,
    description:
      'Why punch things with your bare fists if you can punch them in the ultimate comfort while wearing these over stuffed mittens.',
    tags: ['boxing', 'punching', 'stuffed', 'mittens', 'warm'],
    category: Category.HITTING_THINGS,
    id: '39',
  },
  {
    image: '../../assets/images/cropped/40.jpg',
    thumb: '../../assets/images/thumbs/40.jpg',
    title: 'Used Baseball Glove',
    id: '40',
    price: 12.99,
    description: 'We found this abandoned at the little league field and called finders keepers. We will sell it to you!',
    quantity: 15,
    category: Category.COSTUMES,
    tags: ['baseball', 'lost and found', 'technology', 'balls'],
  },
  {
    image: '../../assets/images/cropped/41.jpg',
    thumb: '../../assets/images/thumbs/41.jpg',
    title: 'Half Glove (white)',
    id: '41',
    price: 14.25,
    description:
      'On hot sumer days, you probably do not want to wear full gloves so we invented half gloves so that you can still look trendy on the baseball court without having sweaty hands.',
    quantity: 22,
    category: Category.COSTUMES,
    tags: ['baseball', 'ball', 'gloves', 'trendy', 'fancy'],
  },
  {
    image: '../../assets/images/cropped/42.jpg',
    thumb: '../../assets/images/thumbs/42.jpg',
    title: 'Old Bat',
    id: '42',
    price: 39.99,
    description: 'We buy old bats from estate sales. Get a surprise bat! Your bat might have been used for baseball. It might have been used to open walnuts. But do not worry bats used in crimes have been turned over to the police.',
    quantity: 10,
    category: Category.HITTING_THINGS,
    tags: ['baseball', 'bat', 'used', 'vintage'],
  },
  {
    image: '../../assets/images/cropped/43.jpg',
    thumb: '../../assets/images/thumbs/43.jpg',
    title: 'Sporty Baby',
    id: '43',
    price: 47.75,
    description: 'Do you need a sporty baby for your next photo shoot? We can help you connect with moms who are willing to dress their babies in sports clothing and bring them to your event.',
    quantity: 12,
    category: Category.COSTUMES,
    tags: ['baby', 'child actors', 'sports kid'],
  },
  {
    image: '../../assets/images/cropped/44.jpg',
    thumb: '../../assets/images/thumbs/44.jpg',
    title: 'Hard Plastic Baseball Hat',
    id: '44',
    price: 21.25,
    description:
      'Are you tired of getting hitint he head with baseballs while wearing flimsy baseball hats? This one is made from hard plastic so balls won\'t hurt you!',
    quantity: 20,
    category: Category.COSTUMES,
    tags: ['hat', 'baseball', 'plastic', 'comfort'],
  },
  {
    image: '../../assets/images/cropped/45.jpg',
    thumb: '../../assets/images/thumbs/45.jpg',
    title: 'Birdie',
    id: '45',
    price: 7.95,
    description:
      'You can hit this plastic birdie with a racket that is sold separately, but not at this store.',
    quantity: 6,
    category: Category.HITTING_THINGS,
    tags: [
      'birdie',
      'accessory',
      'badminton',
      'sold separately',
    ],
  },
  {
    image: '../../assets/images/cropped/46.jpg',
    thumb: '../../assets/images/thumbs/46.jpg',
    title: 'Arrow Shooting Outfit',
    id: '46',
    price: 48.99,
    description:
      'This real fur arrow shooting costume is perfect for standing on mountains and shooting arrows. Get lots of attention!',
    quantity: 18,
    category: Category.COSTUMES,
    tags: ['arrows', 'shooting things', 'fur', 'realistic'],
  },
  {
    image: '../../assets/images/cropped/47.jpg',
    thumb: '../../assets/images/thumbs/47.jpg',
    title: 'Overly Complicated Bow',
    id: '47',
    price: 254.99,
    description:
      'This bow has a lot of pulleys and strings and stuff. It totally works to shoot arrows.',
    quantity: 10,
    category: Category.SHOOTING_THINGS,
    tags: ['arrows', 'shooting things', 'pulleys', 'complicated'],
  },
  {
    image: '../../assets/images/cropped/48.jpg',
    thumb: '../../assets/images/thumbs/48.jpg',
    title: 'Arrow Purse',
    id: '48',
    price: 19.5,
    description:
      'Keep your arrows close with this red felt arrow purse that you can wear on your butt.',
    quantity: 15,
    category: Category.SHOOTING_THINGS,
    tags: ['pocket', 'arrow purse', 'unisex', 'arrow'],
  },
  {
    image: '../../assets/images/cropped/49.jpg',
    thumb: '../../assets/images/thumbs/49.jpg',
    title: 'Horseback Arrow Set',
    id: '49',
    price: 94.99,
    description:
      'This is the perfect set of arrows for riding around on a horse and shooting at things. Extra arrows sold separately because you will probably lose yours.',
    quantity: 12,
    category: Category.SHOOTING_THINGS,
    tags: ['arrows', 'shooting things', 'horseback', 'adjustable height'],
  },
  {
    image: '../../assets/images/cropped/50.jpg',
    thumb: '../../assets/images/thumbs/50.jpg',
    title: 'American Football Outfit',
    id: '50',
    price: 118.5,
    description: 'Comes in a variety of colors, this American Football costume includes a helmet, short pants, long socks, and 80s style shoulder pads.',
    quantity: 20,
    category: Category.COSTUMES,
    tags: ['American Football', 'costume', 'shoulder pads', 'short pants'],
  },
  {
    image: '../../assets/images/cropped/31.jpg',
    thumb: '../../assets/images/thumbs/31.jpg',
    title: 'Golf Sticks',
    price: 43.99,
    description:
      'This is a whole collection of different sticks to hit golf balls with! They have different names and shapes. Ask for one by name to impress the other people on the green.',
    tags: ['golf', 'sticks', 'hitting balls', 'green', 'collection'],
    category: Category.HITTING_THINGS,
    id: '31',
  },
];
